//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class project_online_examinationEntities1 : DbContext
    {
        public project_online_examinationEntities1()
            : base("name=project_online_examinationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<choices> choices { get; set; }
        public virtual DbSet<courses> courses { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<instructor> instructor { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<stud_course> stud_course { get; set; }
        public virtual DbSet<stud_exam> stud_exam { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Topics> Topics { get; set; }
    
        public virtual ObjectResult<coursetopic_Result> coursetopic(Nullable<int> crs_id)
        {
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<coursetopic_Result>("coursetopic", crs_idParameter);
        }
    
        public virtual int deletechoices(Nullable<int> choices_id)
        {
            var choices_idParameter = choices_id.HasValue ?
                new ObjectParameter("choices_id", choices_id) :
                new ObjectParameter("choices_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletechoices", choices_idParameter);
        }
    
        public virtual int deleteCourse(Nullable<int> courseid)
        {
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCourse", courseidParameter);
        }
    
        public virtual int deleteDepartment(Nullable<int> deptnum)
        {
            var deptnumParameter = deptnum.HasValue ?
                new ObjectParameter("deptnum", deptnum) :
                new ObjectParameter("deptnum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteDepartment", deptnumParameter);
        }
    
        public virtual int deleteExam(Nullable<int> exam_id)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("Exam_id", exam_id) :
                new ObjectParameter("Exam_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteExam", exam_idParameter);
        }
    
        public virtual int deleteIns(Nullable<int> insId)
        {
            var insIdParameter = insId.HasValue ?
                new ObjectParameter("insId", insId) :
                new ObjectParameter("insId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteIns", insIdParameter);
        }
    
        public virtual int deleteStud(Nullable<int> studId)
        {
            var studIdParameter = studId.HasValue ?
                new ObjectParameter("studId", studId) :
                new ObjectParameter("studId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteStud", studIdParameter);
        }
    
        public virtual int deletetopic(Nullable<int> topic_id)
        {
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletetopic", topic_idParameter);
        }
    
        public virtual ObjectResult<string> Exam_Correction(Nullable<int> exam_id, Nullable<int> std_id)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("exam_id", exam_id) :
                new ObjectParameter("exam_id", typeof(int));
    
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Exam_Correction", exam_idParameter, std_idParameter);
        }
    
        public virtual int ExamAnswers(Nullable<int> exam_id, Nullable<int> std_id, string a1, string a2, string a3, string a4, string a5, string a6, string a7, string a8, string a9, string a10)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("exam_id", exam_id) :
                new ObjectParameter("exam_id", typeof(int));
    
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var a1Parameter = a1 != null ?
                new ObjectParameter("a1", a1) :
                new ObjectParameter("a1", typeof(string));
    
            var a2Parameter = a2 != null ?
                new ObjectParameter("a2", a2) :
                new ObjectParameter("a2", typeof(string));
    
            var a3Parameter = a3 != null ?
                new ObjectParameter("a3", a3) :
                new ObjectParameter("a3", typeof(string));
    
            var a4Parameter = a4 != null ?
                new ObjectParameter("a4", a4) :
                new ObjectParameter("a4", typeof(string));
    
            var a5Parameter = a5 != null ?
                new ObjectParameter("a5", a5) :
                new ObjectParameter("a5", typeof(string));
    
            var a6Parameter = a6 != null ?
                new ObjectParameter("a6", a6) :
                new ObjectParameter("a6", typeof(string));
    
            var a7Parameter = a7 != null ?
                new ObjectParameter("a7", a7) :
                new ObjectParameter("a7", typeof(string));
    
            var a8Parameter = a8 != null ?
                new ObjectParameter("a8", a8) :
                new ObjectParameter("a8", typeof(string));
    
            var a9Parameter = a9 != null ?
                new ObjectParameter("a9", a9) :
                new ObjectParameter("a9", typeof(string));
    
            var a10Parameter = a10 != null ?
                new ObjectParameter("a10", a10) :
                new ObjectParameter("a10", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExamAnswers", exam_idParameter, std_idParameter, a1Parameter, a2Parameter, a3Parameter, a4Parameter, a5Parameter, a6Parameter, a7Parameter, a8Parameter, a9Parameter, a10Parameter);
        }
    
        public virtual int Exame_Generation(Nullable<int> stu_id, string crs_Name, Nullable<int> quest_id)
        {
            var stu_idParameter = stu_id.HasValue ?
                new ObjectParameter("stu_id", stu_id) :
                new ObjectParameter("stu_id", typeof(int));
    
            var crs_NameParameter = crs_Name != null ?
                new ObjectParameter("crs_Name", crs_Name) :
                new ObjectParameter("crs_Name", typeof(string));
    
            var quest_idParameter = quest_id.HasValue ?
                new ObjectParameter("quest_id", quest_id) :
                new ObjectParameter("quest_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Exame_Generation", stu_idParameter, crs_NameParameter, quest_idParameter);
        }
    
        public virtual int ExamGeneration(Nullable<int> crs_Id, Nullable<int> std_id, Nullable<int> quest_no)
        {
            var crs_IdParameter = crs_Id.HasValue ?
                new ObjectParameter("Crs_Id", crs_Id) :
                new ObjectParameter("Crs_Id", typeof(int));
    
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var quest_noParameter = quest_no.HasValue ?
                new ObjectParameter("quest_no", quest_no) :
                new ObjectParameter("quest_no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExamGeneration", crs_IdParameter, std_idParameter, quest_noParameter);
        }
    
        public virtual ObjectResult<examstudent_Result> examstudent(Nullable<int> exam_id, Nullable<int> stud_id)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("exam_id", exam_id) :
                new ObjectParameter("exam_id", typeof(int));
    
            var stud_idParameter = stud_id.HasValue ?
                new ObjectParameter("stud_id", stud_id) :
                new ObjectParameter("stud_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<examstudent_Result>("examstudent", exam_idParameter, stud_idParameter);
        }
    
        public virtual ObjectResult<firstrepo_Result> firstrepo(Nullable<int> depid)
        {
            var depidParameter = depid.HasValue ?
                new ObjectParameter("depid", depid) :
                new ObjectParameter("depid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<firstrepo_Result>("firstrepo", depidParameter);
        }
    
        public virtual int insertChoices(string choices_id, Nullable<int> question_id, string choice_text)
        {
            var choices_idParameter = choices_id != null ?
                new ObjectParameter("choices_id", choices_id) :
                new ObjectParameter("choices_id", typeof(string));
    
            var question_idParameter = question_id.HasValue ?
                new ObjectParameter("question_id", question_id) :
                new ObjectParameter("question_id", typeof(int));
    
            var choice_textParameter = choice_text != null ?
                new ObjectParameter("choice_text", choice_text) :
                new ObjectParameter("choice_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertChoices", choices_idParameter, question_idParameter, choice_textParameter);
        }
    
        public virtual int insertCourse(Nullable<int> courseid, string coursename)
        {
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(int));
    
            var coursenameParameter = coursename != null ?
                new ObjectParameter("coursename", coursename) :
                new ObjectParameter("coursename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertCourse", courseidParameter, coursenameParameter);
        }
    
        public virtual int insertDepartment(Nullable<int> deptnum, string deptname, Nullable<int> insid)
        {
            var deptnumParameter = deptnum.HasValue ?
                new ObjectParameter("deptnum", deptnum) :
                new ObjectParameter("deptnum", typeof(int));
    
            var deptnameParameter = deptname != null ?
                new ObjectParameter("deptname", deptname) :
                new ObjectParameter("deptname", typeof(string));
    
            var insidParameter = insid.HasValue ?
                new ObjectParameter("insid", insid) :
                new ObjectParameter("insid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertDepartment", deptnumParameter, deptnameParameter, insidParameter);
        }
    
        public virtual int insertExam(Nullable<int> exam_id, Nullable<int> course_id, Nullable<System.DateTime> date)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("Exam_id", exam_id) :
                new ObjectParameter("Exam_id", typeof(int));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertExam", exam_idParameter, course_idParameter, dateParameter);
        }
    
        public virtual int insertStud(string firstname, string lastname, Nullable<int> studId, Nullable<int> studPhone, string passStud)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var studIdParameter = studId.HasValue ?
                new ObjectParameter("studId", studId) :
                new ObjectParameter("studId", typeof(int));
    
            var studPhoneParameter = studPhone.HasValue ?
                new ObjectParameter("studPhone", studPhone) :
                new ObjectParameter("studPhone", typeof(int));
    
            var passStudParameter = passStud != null ?
                new ObjectParameter("passStud", passStud) :
                new ObjectParameter("passStud", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertStud", firstnameParameter, lastnameParameter, studIdParameter, studPhoneParameter, passStudParameter);
        }
    
        public virtual int inserttopics(Nullable<int> topic_id, Nullable<int> course_id, string topic)
        {
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            var topicParameter = topic != null ?
                new ObjectParameter("topic", topic) :
                new ObjectParameter("topic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserttopics", topic_idParameter, course_idParameter, topicParameter);
        }
    
        public virtual ObjectResult<instructorId_Result> instructorId(Nullable<int> inst_id)
        {
            var inst_idParameter = inst_id.HasValue ?
                new ObjectParameter("inst_id", inst_id) :
                new ObjectParameter("inst_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<instructorId_Result>("instructorId", inst_idParameter);
        }
    
        public virtual ObjectResult<selectChoices_Result> selectChoices(Nullable<int> choices_id)
        {
            var choices_idParameter = choices_id.HasValue ?
                new ObjectParameter("choices_id", choices_id) :
                new ObjectParameter("choices_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectChoices_Result>("selectChoices", choices_idParameter);
        }
    
        public virtual ObjectResult<selectCourse_Result> selectCourse(Nullable<int> courseid)
        {
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectCourse_Result>("selectCourse", courseidParameter);
        }
    
        public virtual ObjectResult<selectDepartment_Result> selectDepartment(Nullable<int> deptnum)
        {
            var deptnumParameter = deptnum.HasValue ?
                new ObjectParameter("deptnum", deptnum) :
                new ObjectParameter("deptnum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectDepartment_Result>("selectDepartment", deptnumParameter);
        }
    
        public virtual ObjectResult<selectExam_Result> selectExam(Nullable<int> exam_id)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("Exam_id", exam_id) :
                new ObjectParameter("Exam_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectExam_Result>("selectExam", exam_idParameter);
        }
    
        public virtual ObjectResult<selectIns_Result> selectIns(Nullable<int> insId)
        {
            var insIdParameter = insId.HasValue ?
                new ObjectParameter("insId", insId) :
                new ObjectParameter("insId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectIns_Result>("selectIns", insIdParameter);
        }
    
        public virtual ObjectResult<selectinst_crs_Result> selectinst_crs(Nullable<int> inst_id, Nullable<int> crs_id)
        {
            var inst_idParameter = inst_id.HasValue ?
                new ObjectParameter("inst_id", inst_id) :
                new ObjectParameter("inst_id", typeof(int));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectinst_crs_Result>("selectinst_crs", inst_idParameter, crs_idParameter);
        }
    
        public virtual ObjectResult<selectStud_Result> selectStud(Nullable<int> stdId)
        {
            var stdIdParameter = stdId.HasValue ?
                new ObjectParameter("stdId", stdId) :
                new ObjectParameter("stdId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectStud_Result>("selectStud", stdIdParameter);
        }
    
        public virtual ObjectResult<selectstud_crs_Result> selectstud_crs(Nullable<int> std_id, Nullable<int> crs_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var crs_idParameter = crs_id.HasValue ?
                new ObjectParameter("crs_id", crs_id) :
                new ObjectParameter("crs_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectstud_crs_Result>("selectstud_crs", std_idParameter, crs_idParameter);
        }
    
        public virtual ObjectResult<selectstud_exam_Result> selectstud_exam(Nullable<int> std_id, Nullable<int> que_id, Nullable<int> exam_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            var que_idParameter = que_id.HasValue ?
                new ObjectParameter("que_id", que_id) :
                new ObjectParameter("que_id", typeof(int));
    
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("exam_id", exam_id) :
                new ObjectParameter("exam_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectstud_exam_Result>("selectstud_exam", std_idParameter, que_idParameter, exam_idParameter);
        }
    
        public virtual ObjectResult<selectTopics_Result> selectTopics(Nullable<int> topic_id)
        {
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectTopics_Result>("selectTopics", topic_idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<studentinfo_Result> studentinfo(Nullable<int> dpetid)
        {
            var dpetidParameter = dpetid.HasValue ?
                new ObjectParameter("dpetid", dpetid) :
                new ObjectParameter("dpetid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<studentinfo_Result>("studentinfo", dpetidParameter);
        }
    
        public virtual int updateChoices(Nullable<int> choices_id, string choice_text)
        {
            var choices_idParameter = choices_id.HasValue ?
                new ObjectParameter("choices_id", choices_id) :
                new ObjectParameter("choices_id", typeof(int));
    
            var choice_textParameter = choice_text != null ?
                new ObjectParameter("choice_text", choice_text) :
                new ObjectParameter("choice_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateChoices", choices_idParameter, choice_textParameter);
        }
    
        public virtual int updateCourse(Nullable<int> courseid, string coursename)
        {
            var courseidParameter = courseid.HasValue ?
                new ObjectParameter("courseid", courseid) :
                new ObjectParameter("courseid", typeof(int));
    
            var coursenameParameter = coursename != null ?
                new ObjectParameter("coursename", coursename) :
                new ObjectParameter("coursename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateCourse", courseidParameter, coursenameParameter);
        }
    
        public virtual int updateDepartment(Nullable<int> deptnum, string deptname)
        {
            var deptnumParameter = deptnum.HasValue ?
                new ObjectParameter("deptnum", deptnum) :
                new ObjectParameter("deptnum", typeof(int));
    
            var deptnameParameter = deptname != null ?
                new ObjectParameter("deptname", deptname) :
                new ObjectParameter("deptname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateDepartment", deptnumParameter, deptnameParameter);
        }
    
        public virtual int updateExam(Nullable<int> exam_id, Nullable<int> crsid)
        {
            var exam_idParameter = exam_id.HasValue ?
                new ObjectParameter("Exam_id", exam_id) :
                new ObjectParameter("Exam_id", typeof(int));
    
            var crsidParameter = crsid.HasValue ?
                new ObjectParameter("crsid", crsid) :
                new ObjectParameter("crsid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateExam", exam_idParameter, crsidParameter);
        }
    
        public virtual int updateIns(string insName, Nullable<int> insId, Nullable<int> sal)
        {
            var insNameParameter = insName != null ?
                new ObjectParameter("insName", insName) :
                new ObjectParameter("insName", typeof(string));
    
            var insIdParameter = insId.HasValue ?
                new ObjectParameter("insId", insId) :
                new ObjectParameter("insId", typeof(int));
    
            var salParameter = sal.HasValue ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateIns", insNameParameter, insIdParameter, salParameter);
        }
    
        public virtual int updateStud(Nullable<int> studPhone, string studPassword, Nullable<int> studId)
        {
            var studPhoneParameter = studPhone.HasValue ?
                new ObjectParameter("studPhone", studPhone) :
                new ObjectParameter("studPhone", typeof(int));
    
            var studPasswordParameter = studPassword != null ?
                new ObjectParameter("studPassword", studPassword) :
                new ObjectParameter("studPassword", typeof(string));
    
            var studIdParameter = studId.HasValue ?
                new ObjectParameter("studId", studId) :
                new ObjectParameter("studId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateStud", studPhoneParameter, studPasswordParameter, studIdParameter);
        }
    
        public virtual int updatetopic(Nullable<int> topic_id, string topic_Name)
        {
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            var topic_NameParameter = topic_Name != null ?
                new ObjectParameter("topic_Name", topic_Name) :
                new ObjectParameter("topic_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatetopic", topic_idParameter, topic_NameParameter);
        }
    }
}
