//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class stud_course
    {
        public int course_id { get; set; }
        public int stud_id { get; set; }
        public Nullable<int> student_grade { get; set; }
    
        public virtual courses courses { get; set; }
        public virtual student student { get; set; }
    }
}
